<?php

namespace ContainerVlgM0oi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_35sFjx3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.35sFjx3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.35sFjx3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pictureRepository' => ['privates', 'App\\Repository\\PictureRepository', 'getPictureRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'pictureRepository' => 'App\\Repository\\PictureRepository',
            'serializer' => '?',
            'urlGenerator' => '?',
        ]);
    }
}
