<?php

namespace ContainerVlgM0oi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RFpWCIjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rFpWCIj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rFpWCIj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Ingredient' => ['privates', '.errored..service_locator.rFpWCIj.App\\Entity\\Ingredient', NULL, 'Cannot autowire service ".service_locator.rFpWCIj": it references class "App\\Entity\\Ingredient" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'Ingredient' => 'App\\Entity\\Ingredient',
            'entityManager' => '?',
        ]);
    }
}
