<?php

namespace ContainerVlgM0oi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CW6rrmwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cW6rrmw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cW6rrmw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'ingredientRepository' => ['privates', 'App\\Repository\\IngredientRepository', 'getIngredientRepositoryService', true],
            'recette' => ['privates', '.errored..service_locator.cW6rrmw.App\\Entity\\Recette', NULL, 'Cannot autowire service ".service_locator.cW6rrmw": it references class "App\\Entity\\Recette" but no such service exists.'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'entityManager' => '?',
            'ingredientRepository' => 'App\\Repository\\IngredientRepository',
            'recette' => 'App\\Entity\\Recette',
            'serializer' => '?',
            'urlGenerator' => '?',
        ]);
    }
}
