<?php

namespace Container83dxxxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6O2RgTDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6O2RgTD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6O2RgTD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recette' => ['privates', '.errored..service_locator.6O2RgTD.App\\Entity\\Recette', NULL, 'Cannot autowire service ".service_locator.6O2RgTD": it references class "App\\Entity\\Recette" but no such service exists.'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'recette' => 'App\\Entity\\Recette',
            'serializer' => '?',
        ]);
    }
}
