<?php

namespace Container83dxxxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J08NWacService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j08NWac' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j08NWac'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IngredientController::createIngredient' => ['privates', '.service_locator.EfpQm6T', 'get_ServiceLocator_EfpQm6TService', true],
            'App\\Controller\\IngredientController::deleteIngredient' => ['privates', '.service_locator.rFpWCIj', 'get_ServiceLocator_RFpWCIjService', true],
            'App\\Controller\\IngredientController::getAllIngredients' => ['privates', '.service_locator.PSMRMAc', 'get_ServiceLocator_PSMRMAcService', true],
            'App\\Controller\\IngredientController::getIngredients' => ['privates', '.service_locator.WWHc.ST', 'get_ServiceLocator_WWHc_STService', true],
            'App\\Controller\\IngredientController::updateIngredient' => ['privates', '.service_locator.ZhewDLY', 'get_ServiceLocator_ZhewDLYService', true],
            'App\\Controller\\PictureController::createPicture' => ['privates', '.service_locator.kbr8elP', 'get_ServiceLocator_Kbr8elPService', true],
            'App\\Controller\\PictureController::getPicture' => ['privates', '.service_locator.35sFjx3', 'get_ServiceLocator_35sFjx3Service', true],
            'App\\Controller\\RecetteController::createRecette' => ['privates', '.service_locator.FlinONa', 'get_ServiceLocator_FlinONaService', true],
            'App\\Controller\\RecetteController::deleteRecette' => ['privates', '.service_locator.jQc1PsA', 'get_ServiceLocator_JQc1PsAService', true],
            'App\\Controller\\RecetteController::getAllRecettes' => ['privates', '.service_locator.z9XZMOj', 'get_ServiceLocator_Z9XZMOjService', true],
            'App\\Controller\\RecetteController::getRecette' => ['privates', '.service_locator.6O2RgTD', 'get_ServiceLocator_6O2RgTDService', true],
            'App\\Controller\\RecetteController::updateRecette' => ['privates', '.service_locator.cW6rrmw', 'get_ServiceLocator_CW6rrmwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\IngredientController:createIngredient' => ['privates', '.service_locator.EfpQm6T', 'get_ServiceLocator_EfpQm6TService', true],
            'App\\Controller\\IngredientController:deleteIngredient' => ['privates', '.service_locator.rFpWCIj', 'get_ServiceLocator_RFpWCIjService', true],
            'App\\Controller\\IngredientController:getAllIngredients' => ['privates', '.service_locator.PSMRMAc', 'get_ServiceLocator_PSMRMAcService', true],
            'App\\Controller\\IngredientController:getIngredients' => ['privates', '.service_locator.WWHc.ST', 'get_ServiceLocator_WWHc_STService', true],
            'App\\Controller\\IngredientController:updateIngredient' => ['privates', '.service_locator.ZhewDLY', 'get_ServiceLocator_ZhewDLYService', true],
            'App\\Controller\\PictureController:createPicture' => ['privates', '.service_locator.kbr8elP', 'get_ServiceLocator_Kbr8elPService', true],
            'App\\Controller\\PictureController:getPicture' => ['privates', '.service_locator.35sFjx3', 'get_ServiceLocator_35sFjx3Service', true],
            'App\\Controller\\RecetteController:createRecette' => ['privates', '.service_locator.FlinONa', 'get_ServiceLocator_FlinONaService', true],
            'App\\Controller\\RecetteController:deleteRecette' => ['privates', '.service_locator.jQc1PsA', 'get_ServiceLocator_JQc1PsAService', true],
            'App\\Controller\\RecetteController:getAllRecettes' => ['privates', '.service_locator.z9XZMOj', 'get_ServiceLocator_Z9XZMOjService', true],
            'App\\Controller\\RecetteController:getRecette' => ['privates', '.service_locator.6O2RgTD', 'get_ServiceLocator_6O2RgTDService', true],
            'App\\Controller\\RecetteController:updateRecette' => ['privates', '.service_locator.cW6rrmw', 'get_ServiceLocator_CW6rrmwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\IngredientController::createIngredient' => '?',
            'App\\Controller\\IngredientController::deleteIngredient' => '?',
            'App\\Controller\\IngredientController::getAllIngredients' => '?',
            'App\\Controller\\IngredientController::getIngredients' => '?',
            'App\\Controller\\IngredientController::updateIngredient' => '?',
            'App\\Controller\\PictureController::createPicture' => '?',
            'App\\Controller\\PictureController::getPicture' => '?',
            'App\\Controller\\RecetteController::createRecette' => '?',
            'App\\Controller\\RecetteController::deleteRecette' => '?',
            'App\\Controller\\RecetteController::getAllRecettes' => '?',
            'App\\Controller\\RecetteController::getRecette' => '?',
            'App\\Controller\\RecetteController::updateRecette' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\IngredientController:createIngredient' => '?',
            'App\\Controller\\IngredientController:deleteIngredient' => '?',
            'App\\Controller\\IngredientController:getAllIngredients' => '?',
            'App\\Controller\\IngredientController:getIngredients' => '?',
            'App\\Controller\\IngredientController:updateIngredient' => '?',
            'App\\Controller\\PictureController:createPicture' => '?',
            'App\\Controller\\PictureController:getPicture' => '?',
            'App\\Controller\\RecetteController:createRecette' => '?',
            'App\\Controller\\RecetteController:deleteRecette' => '?',
            'App\\Controller\\RecetteController:getAllRecettes' => '?',
            'App\\Controller\\RecetteController:getRecette' => '?',
            'App\\Controller\\RecetteController:updateRecette' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
