<?php

namespace Container83dxxxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecette3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jQc1PsA.App\Entity\Recette' shared service.
     *
     * @return \App\Entity\Recette
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jQc1PsA": it references class "App\\Entity\\Recette" but no such service exists.');
    }
}
