<?php

namespace ContainerTMMKlex;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIngredient3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rFpWCIj.App\Entity\Ingredient' shared service.
     *
     * @return \App\Entity\Ingredient
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rFpWCIj": it references class "App\\Entity\\Ingredient" but no such service exists.');
    }
}
