<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMMKlex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMMKlex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMMKlex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMMKlex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTMMKlex\App_KernelDevDebugContainer([
    'container.build_hash' => 'TMMKlex',
    'container.build_id' => '800f202d',
    'container.build_time' => 1666684827,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMMKlex');
