<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQJaZSD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQJaZSD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXQJaZSD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXQJaZSD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXQJaZSD\App_KernelDevDebugContainer([
    'container.build_hash' => 'XQJaZSD',
    'container.build_id' => '58bc89af',
    'container.build_time' => 1666687278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQJaZSD');
